version: '3.7'
services:
  isolated-tests:
    image: harbor.intgdc.com/tools/gdc-node-chrome:8.12.0_67.0.3396
    volumes:
      - ./:/mastercard:rw
    command: ./scripts/run-testcafe-ci.sh
    working_dir: /mastercard
    user: '$USER_UID:$USER_GID'
    depends_on:
      - mastercard-fi-ui
    environment:
      - TEST_BACKEND=http://mastercard-fi-ui:8080/fraudinsights
      - TEST_PATH=test/**/**/isolated/*_test*

  mastercard-fi-ui:
    image: $IMAGE_ID
    volumes:
        - ./nginx/proxy-isolated-tests.conf:/etc/nginx/extra-conf.d/proxy-isolated-tests.conf
    depends_on:
      - backend-mock

  backend-mock:
    image: harbor.intgdc.com/3rdparty/rodolpheche/wiremock
    volumes:
      - ./test-services/backend-mock/:/home/wiremock:ro
      
