---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "mastercard-fi.fullname" . }}-mastercard-fi-netpol
  labels:
    team: honeybadgers
    app.kubernetes.io/name: {{ include "mastercard-fi.name" . }}
    helm.sh/chart: {{ include "mastercard-fi.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: ui
    app.kubernetes.io/part-of: mastercard-fi
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ include "mastercard-fi.name" . }}
      app.kubernetes.io/component: ui
      app.kubernetes.io/instance: {{ .Release.Name }}
  policyTypes:
    - Egress
  egress:
    - ports:
        - protocol: UDP
          port: 53 # DNS
        - protocol: UDP
          port: 514 # rsyslog
    - to:
      - namespaceSelector:
          matchLabels:
            name: istio-system
