apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ template "mastercard-fi.fullname" . }}-ui-gateway-http
  labels:
    team: honeybadgers
    app.kubernetes.io/name: {{ include "mastercard-fi.name" . }}
    helm.sh/chart: {{ include "mastercard-fi.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: ui
    app.kubernetes.io/part-of: mastercard-fi
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 80
      name: http-{{ template "mastercard-fi.fullname" . }}-ui
      protocol: HTTP
    hosts:
    - {{ .Values.webapp.mastercardFi.uiDevelop.service.ingressHost }}
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ template "mastercard-fi.fullname" . }}-ui-service-http
  labels:
    team: honeybadgers
    app.kubernetes.io/name: {{ include "mastercard-fi.name" . }}
    helm.sh/chart: {{ include "mastercard-fi.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: ui
    app.kubernetes.io/part-of: mastercard-fi
spec:
  hosts:
    - {{ .Values.webapp.mastercardFi.uiDevelop.service.ingressHost }}
  gateways:
    - {{ template "mastercard-fi.fullname" . }}-ui-gateway-http
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: {{ template "mastercard-fi.fullname" . }}-ui.{{ .Release.Namespace }}.svc.cluster.local
            port:
              number: 8080
